version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 5
    versioning-strategy: increase
    ignore:
      - dependency-name: 'react'
        update-types:
          - 'version-update:semver-major'
      - dependency-name: 'react-native'
        update-types:
          - 'version-update:semver-major'
      - dependency-name: '@types/react'
        update-types:
          - 'version-update:semver-major'
    groups:
      expo:
        patterns:
          - '^expo'
          - '^@expo'
      react-ecosystem:
        patterns:
          - '^react(-.*)?$'
          - '^@react(-.*)?$'
          - '^react-native'
          - '^@react-native'
          - '^@react-navigation'
      i18n:
        patterns:
          - '^i18next$'
          - '^react-i18next$'
      tanstack:
        patterns:
          - 'tanstack'
          - '^@tanstack'
      testing:
        patterns:
          - '^@testing-library/'
          - '^jest'
      development:
        dependency-type: 'development'
        update-types:
          - 'minor'
          - 'patch'
