version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 10
    versioning-strategy: increase
    ignore:
      - dependency-name: 'react'
        update-types:
          - 'version-update:semver-major'
      - dependency-name: 'react-native'
        update-types:
          - 'version-update:semver-major'
      - dependency-name: '@types/react'
        update-types:
          - 'version-update:semver-major'
    groups:
      expo:
        patterns:
          - 'expo*'
          - '@expo*'
      react-native:
        patterns:
          - 'react-native*'
          - '@react-native*'
      testing:
        patterns:
          - '@testing-library/*'
          - 'jest*'
      development:
        dependency-type: 'development'
        update-types:
          - 'minor'
          - 'patch'
